---
title: "Untitled"
author: "Hong Shi"
date: "4/13/2021"
output: pdf_document
---
```{r}
library(tidyverse)
library(here)
```

```{r}
lso <- clean_data
lso <- lso %>% filter(dist_from_cut <= 0.3 & dist_from_cut >= -0.3)
```

```{r}
lso <- lso %>% filter(lowHS ==1)
```

```{r}
vec <- seq(-0.3, 0.3, 0.05)
add <- rep(NA, 7)

lso <- lso %>% mutate(left_school_hat = NA)
lso <- lso %>% dplyr::select(c(left_school, dist_from_cut, gpalscutoff,
                               gpaXgpalscutoff, gpaXgpagrcutoff, 
                               left_school_hat, dist_from_cut_med10))

for(i in seq_along(vec)){
  reg <- lm(left_school~gpalscutoff+gpaXgpalscutoff+gpaXgpagrcutoff,
            data = subset(lso, dist_from_cut >= vec[i]-0.6 & 
                            dist_from_cut <= vec[i]+0.6))
  print(summary(reg))
  add[2] <- vec[i]
  add[3] <- as.numeric(add[2] < 0)
  add[4] <- add[3]*add[2]
  add[5] <- add[2]*(1-add[3])
  lso <- rbind(lso, add)
  lso[length(lso$dist_from_cut), 6] <- 
    as.numeric(predict(reg, lso)[length(lso$dist_from_cut)]) 
}

# collapse data using variable dist_from_cut_med10, by calculating
# averages for left_school for every dist_from_cut_med10
lso1 <- lso %>% group_by(dist_from_cut_med10) %>%
  summarise(left_school = mean(left_school)) %>% print

lso1 <- lso1 %>% rename(dist_from_cut = dist_from_cut_med10)
lso1 <- lso1 %>% mutate(gpalscutoff = NA, gpaXgpalscutoff = NA,
                        gpaXgpagrcutoff = NA, left_school_hat = NA,
                        dist_from_cut_med10 = NA)
lso1 <- lso1 %>% dplyr::select(c(left_school, dist_from_cut, gpalscutoff, 
                                 gpaXgpalscutoff, gpaXgpagrcutoff, 
                                 left_school_hat, dist_from_cut_med10))
lso_add <- lso[17208:17256,]
lso1 <- rbind(lso1, lso_add); rm(lso_add)

lso1 <- lso1 %>% mutate(group_freq = ifelse(dist_from_cut>0, 1, 0))

rdplot(lso1$left_school, lso1$dist_from_cut, c=0, p=2,
       x.label="1st Year GPA Minus Probation Cutoff", 
       y.label="Left University Voluntarily", title="Figure 3",
       numbinl=10, numbinr=10, lowerend = -1.5, upperend = 1.5,
       type.dots="o")

plot3 <- lso1 %>% 
  ggplot(aes(x=dist_from_cut, y=left_school, group=group_freq))+
  geom_point(size=1.5)+geom_smooth(method = "loess", linetype=2)+
  geom_vline(xintercept = 0, linetype = 3)+theme_bw()+
  xlab("1st Year GPA Minus Probation Cutoff")+
  ylab("Left University Voluntarily")+ggtitle("Figure 3")+
  scale_x_continuous(breaks=seq(-1.5, 1.5, 0.5))+
  theme(legend.position="none")
plot3
```

```{r}
reg_ex <- felm(nextGPA~gpalscutoff+gpaXgpalscutoff+
                 gpaXgpagrcutoff|0|0|clustervar,
               data = subset(clean_cut, male == 1))
summary(reg_ex)
```

```{r}
reg_ex <- felm(nextGPA~ probation_year1+gpaXgpalscutoff+
                 gpaXgpagrcutoff|0|0|dist_from_cut,
               data = subset(clean_cut, male == 1))
summary(reg_ex)
class(clean_cut$probation_year1)
```

```{r}
class(clean_cut$status)
clean_cut$status <- as.factor(clean_cut$status)
levels(clean_cut$status)
# Set students on academic probation as the reference group
clean_cut$status <- relevel(clean_cut$status, "On Academic Probation")
clean_cut2$status <- as.factor(clean_cut2$status)
clean_cut2$status <- relevel(clean_cut2$status, "On Academic Probation")
clean_cut3$status <- as.factor(clean_cut3$status)
clean_cut3$status <- relevel(clean_cut3$status, "On Academic Probation")
```

```{r}
?coef_rename

gpa_model <- lm(GPA_year2 ~ status + dist_from_cut + gender + highHS + first_language, data = clean_cut)
test_gpa_model <- gpa_model
class(clean_cut$first_language)
test_gpa_model$coefficients
```

```{r}
stargazer(test_gpa_model)
```

```{r}
# Refer the following to create model summary table https://vincentarelbundock.github.io/modelsummary/articles/modelsummary.html
modelsummary(test_gpa_model,
             stars =TRUE,
             coef_rename = c("(Intercept)" = "Constant", "statusIn Good Standing" = "In Good Standing", "dist_from_cut" = "f(Cutoff Distance)", "genderMale" = "Gender Male", "highHS" = "Highschool Above Average", "first_languageOther" = "First Language Not English "))
```

```{r}
modelsummary(gpa_model,
             stars = TRUE,
             coef_rename = )
```

```{r}
gpa_model <- lm(GPA_year2 ~ status + dist_from_cut + gender + highHS + first_language, data = clean_cut)
summary(gpa_model)
```
```{r}
plot(gpa_model)
```
```{r}
cut_data_lin <- clean_for_summary %>% 
  filter(dist_from_cut >= -0.6, dist_from_cut <= 0.6)

#Filter invalid data caused by university administrative error in data reporting

clean_cut2 <- cut_data_lin %>% 
  filter((dist_from_cut < 0 & probation_year1 ==1)| (dist_from_cut >=0 & probation_year1 ==0) )

clean_cut2 <- clean_cut2 %>% 
  mutate( status = case_when(probation_year1 == 0 ~ "In Good Standing",
                             probation_year1 == 1 ~ "On Academic Probation"))

cut_data3 <- clean_for_summary %>% 
  filter(dist_from_cut >= -0.3, dist_from_cut <= 0.3)
clean_cut3 <- cut_data3 %>%
  filter((dist_from_cut < 0 & probation_year1 ==1)| (dist_from_cut >=0 & probation_year1 ==0) )
clean_cut3 <- clean_cut3 %>% 
    mutate( status = case_when(probation_year1 == 0 ~ "In Good Standing",
                             probation_year1 == 1 ~ "On Academic Probation"))

```

```{r}
#test_dropout_model2$coefficients
#test_dropout_model <- dropout_model
modelsummary(list("Bandwidth of 0.2 GPA" = test_dropout_model, "Bandwidth of 0.1 GPA" = test_dropout_model3,"Bandwidth of 0.6 GPA" =  test_dropout_model2),
             stars =TRUE,
             coef_map = c("(Intercept)" = "Constant", "statusIn Good Standing" = "In Good Standing", "dist_from_cut" = "f(Cutoff Distance)", "genderMale" = "Gender Male", "highHS" = "Highschool Above Average", "first_languageOther" = "First Language Not English ")
             ,exponentiate = TRUE
             ) %>% 
  add_footnote("test note", notation = "number")
```
```{r}
test_dropout_model2 <- glm(left_school ~ status + dist_from_cut + gender + highHS + first_language ,family = "binomial", data = clean_cut2)
```

```{r}
test_dropout_model3 <- glm(left_school ~ status + dist_from_cut + gender + highHS + first_language ,family = "binomial", data = clean_cut3)
```

```{r}
dropout_model <- glm(left_school ~ status + dist_from_cut + gender + highHS + first_language ,family = "binomial", data = clean_cut)
summary(dropout_model)
```

```{r}
fixed_dum1 <- glm(gradin4 ~ status + dist_from_cut,family = "binomial", data = clean_cut)
summary(fixed_dum1)
```

```{r}

grad_model <- glm(gradin4 ~ status + dist_from_cut + gender + highHS + first_language,family = "binomial", data = clean_cut)
summary(grad_model)
```

```{r}
?modelsummary
```


```{r}
## modelsummary
library(modelsummary)
modelsummary(gpa_model)
```

```{r}
rdplot(y = clean_for_summary$left_school, x = clean_for_summary$dist_from_cut, c = 0)
a1 <- rdrobust( y = clean_cut$left_school, x = clean_cut$dist_from_cut,c=0)
a2 <- rdrobust( y = clean_for_summary$left_school, x = clean_for_summary$dist_from_cut, c=0)
IKbandwidth( clean_for_summary$left_school, clean_for_summary$dist_from_cut, cutpoint=0)
IKbandwidth( clean_cut$left_school, clean_cut$dist_from_cut, cutpoint=0)
IKbandwidth(clean_for_summary$dist_from_cut,clean_for_summary$year2_dist_from_cut, cutpoint = 0, verbose = TRUE)
summary(a1)
summary(a2)
```
```{r}
rdplot(y = clean_cut$left_school, x = clean_cut$dist_from_cut, c = 0)
```

