---
title: "EDA"
author: "Hong Shi"
date: "4/6/2021"
output: pdf_document
---
```{r}
library(tidyverse)
library(here)
library(haven)
library(rdrobust)
library(finalfit)
```

```{r}
raw_data <- read_dta(here("inputs/data/original_data.dta"))
```

```{r}
sum(is.na(raw_data$hsgrade_pct))

```
```{r}
class(raw_data$loc_campus1)
```

```{r}
eda_clean <- 
  raw_data %>% 
  mutate(loc_campus = 
           case_when(
             loc_campus1 == 1 ~ "Campus 1",
             loc_campus2 == 1 ~ "Campus 2",
             loc_campus3 == 1 ~ "Campus 3"
           ))
```

```{r}
boxplot(hsgrade_pct~loc_campus,
        data = eda_clean)

```
```{r}
boxplot(GPA_year1~loc_campus,
        data = eda_clean)
```
```{r}
boxplot(GPA_year2~loc_campus,
        data = eda_clean)
```

```{r}
hgrade_by_campus <- 
  ggplot(eda_clean, aes(x = loc_campus, y = hsgrade_pct, fill = loc_campus))+
  geom_boxplot()+
  theme_minimal()+
  labs(
    title = "Distribution of High School Grade by Campus",
    x = "Campus",
    y = "High School Grade Percentile"
  )+
  theme(plot.title = element_text(hjust = 0.5),
        legend.position = "none")
hgrade_by_campus
```

```{r}
hschool_test <- aov(hsgrade_pct ~ loc_campus, data = eda_clean)
summary(hschool_test)
```
```{r}
library(VIM)
aggr(eda_clean, prop = FALSE, numbers = TRUE)
```

